### ISSUE TITLE
[EPIC] Ingredients feature

### ISSUE THREAD

**Issue by johnnycopes** [johnnycopes/atocha#302]
#### OVERVIEW

The next major step for MM is to add the concept of "ingredients". Doing so will push the app from being a meal planning tool towards being a full-blown kitchen management system.

Simply put: an ingredient is a building block of a dish. It has a name, a type, and a list of IDs referring to the dishes that rely on it. The type is a new category to help broadly define it (e.g. spice, meat/seafood, refrigerated). For now, the ingredient types will be predefined by MM and are not configurable. However, they're intended to be intuitive and general.

NOTE: the ingredient types pretty well to the different areas of a typical supermarket, which is intentional: the next major planned feature is the Shopping List, which will parse the ingredients of active dishes and compile a shopping list for the user, sorted by supermarket section for convenience.

#### SCOPE OF WORK

Much of this feature will be familiar: creating a new entity in the database, adding logic to fetch it, and passing it through all the way to the visible UI layer. A two-way link needs to exist between dishes and ingredients (the same as how it does for dishes and meals or dishes and tags). There will need to be a new feature area of the app dedicated to viewing and managing the ingredients in isolation (e.g. menu-matriach.web.app/ingredients).

The significant difference between ingredients and the other entities (and thus, the reason for deferring this feature initially) is the creation process. Adding menus and dishes (and creating meals from entered dishes) is a very personal process. It's not realistic for MM to make any assumptions about the dishes a user might like to make except to provide some initial seed data as an example. Consequently, nothing can be assumed about menus or meals either because they're comprised of dishes

Ingredients, however, are more crude and more numerous. If I have 10 dishes in my account, they could easily be comprised of over 100 unique ingredients in total. Having to manually add 100 ingredients is both unrealistic and a tedious waste of time -- a bell pepper is the same thing whether it's in my dish or your dish, and it will be found in the produce section of any supermarket on the planet. Why should we both need to manually enter that information?

Therefore, a major component of this feature will be to define a list in the database of reasonably common ingredients (likely a few thousand) that will be offered as suggested options when users are creating their dishes. They should be customizable (for example, if a user is from the UK and prefers "aubergine" to "eggplant"), but it should be rare that they have to register an entirely new ingredient.

#### TASKS

All work will be merged into the feature branch `mm-ingredients` until it's completely ready

2. [x] https://github.com/johnnycopes/atocha/issues/303
3. [x] https://github.com/johnnycopes/atocha/issues/312
4. [x] https://github.com/johnnycopes/atocha/issues/314
5. [x] https://github.com/johnnycopes/atocha/issues/317
6. [x] https://github.com/johnnycopes/atocha/issues/320
7. [x] https://github.com/johnnycopes/atocha/issues/324
8. [x] https://github.com/johnnycopes/atocha/issues/331
9. [x] https://github.com/johnnycopes/atocha/issues/335

**Comment by johnnycopes** [comment]
After significant work on this feature, I think the Ingredients foundations are in place. An overview of what was accomplished/not accomplished, as it differs from the original vision at the outset:

**ACCOMPLISHED:**

1. **Ingredients route**. A Kanban board view is shown with all expected CRUD actions
2. **Configurable ingredient types**. Ingredients only have one type, but an ingredient type can belong to many ingredients
3. **Link between dishes and ingredients**. Dishes and ingredients have a many-to-many relationship

**NOT ACCOMPLISHED:**

1. **System ingredients concept** ([#327](https://github.com/johnnycopes/atocha/issues/327)). This needs to be reconsidered now that ingredient types are dynamic, plus there are plenty of changes to be merged in this epic already
2. **Sophisticated ingredient entry**. For the sake of simplicity and continued convention, the user flow of needing to first go to the entity-specific route in order to make changes to entities that can be seen in other routes is continued here
3. **Meaningful usage of ingredients**. Even though they can be created and added to dishes, ingredients aren't useful yet. The main purpose behind them will be in the upcoming shopping list feature
